image: maven:3.8.1-jdk-8

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - "mvn package"
  artifacts:
    name: "BungeeReconnect"
    paths:
      - "./target/Bungee-Reconnect*"